dist: bionic
language: crystal

addons:
  postgresql: "12"
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12
    - libgit2-dev
    - libsass-dev

crystal:
- latest

services:
- postgresql

cache: shards

env:
  global:
    - PGPORT: 5433
    - TEST_DATABASE_URL: "postgres://postgres:@localhost:5433/shardbox"

before_install:
- |
  mkdir -p vendor/bin
  wget -qO vendor/bin/dbmate https://github.com/amacneil/dbmate/releases/download/v1.7.0/dbmate-linux-amd64
  chmod +x vendor/bin/dbmate
  export PATH="$PATH:$(pwd)/vendor/bin"

before_script:
- |
  sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  sudo service postgresql restart
  psql -U postgres -c 'SELECT version()'
- make -C lib/shardbox-core test_db

jobs:
  include:
  - stage: test
    name: unit tests
    script: crystal spec
  - stage: test
    name: crystal format
    script: crystal tool format src spec --check
  - stage: integration_test
    script: |
      make bin/app
      export DATABASE_URL=$TEST_DATABASE_URL
      bin/app &
      sleep 1
      curl http://localhost:3000/ -v > /dev/null
