dist: bionic
language: crystal

build_addons: &build_addons
  postgresql: "12"
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12
    - libgit2-dev
    - libsass-dev

crystal:
- latest

cache: shards

env:
  global:
    - PGPORT: 5433
    - TEST_DATABASE_URL: "postgres://postgres:@localhost:5433/shardbox"

jobs:
  include:
  - stage: test
    name: unit tests
    services:
    - postgresql
    addons: *build_addons
    before_script: ./.travis/setup-database.sh
    script: crystal spec
  - stage: test
    name: crystal format
    install: skip
    script: crystal tool format src spec --check
  - stage: integration_test
    services:
    - postgresql
    addons: *build_addons
    before_script: ./.travis/setup-database.sh
    script: ./.travis/integration-spec.sh
  - stage: build docker image
    language: generic
    script: docker build -t $DEPLOY_IMAGE:b$TRAVIS_BUILD_NUMBER .
    services:
    - docker
    deploy:
      script: docker save $DEPLOY_IMAGE:b$TRAVIS_BUILD_NUMBER | ssh $DEPLOY_HOST "$DEPLOY_COMMAND"
      branch: master
