dist: bionic
language: crystal

build_addons: &build_addons
  postgresql: "12"
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12
    - libgit2-dev
    - libsass-dev

crystal:
- latest

cache: shards

env:
  global:
    - PGPORT: 5433
    - TEST_DATABASE_URL: "postgres://postgres:@localhost:5433/shardbox"

jobs:
  include:
  - stage: test
    name: unit tests
    services:
    - postgresql
    addons: *build_addons
    before_script: ./.travis/setup-database.sh
    script: crystal spec
  - stage: test
    name: crystal format
    install: skip
    script: crystal tool format src spec --check
  - stage: integration_test
    services:
    - postgresql
    addons: *build_addons
    before_script: ./.travis/setup-database.sh
    script: ./.travis/integration-spec.sh
  - stage: build docker image
    language: generic
    services:
    - docker
    addons:
      ssh_known_hosts: shardbox.org
    env:
      DEPLOY_IMAGE: dokku/shardbox
    script: docker build -t $DEPLOY_IMAGE:b$TRAVIS_BUILD_NUMBER .
    before_deploy:
    -
    deploy:
      provider: script
      script:
      - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > private_ssh_key
      - docker save $DEPLOY_IMAGE:b$TRAVIS_BUILD_NUMBER | ssh -i private_ssh_key dokku@shardbox.org "docker load | dokku tags:deploy shardbox b$TRAVIS_BUILD"
      on:
        branch: master
